[features]
seeds = false
skip-lint = false
[programs.localnet]
certification_requirement_be = "76ksujnwvqsPq2V9gfKYgRn1adzw4XifKncbstfSxLCb"

[programs.devnet]
certification_requirement_be = "76ksujnwvqsPq2V9gfKYgRn1adzw4XifKncbstfSxLCb"

[registry]
url = "https://api.devnet.solana.com"

# "http://localhost:8899"

[provider]
cluster = "devnet"
wallet = "/home/jayson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
