[features]
seeds = false
skip-lint = false
[programs.localnet]
certification_requirement_be = "CKomVJRHhV6PKvkg2KuDsXnwzTJNXPy3KP42nFvvWwsF"

[registry]
url = "http://localhost:8899"

[provider]
cluster = "Localnet"
wallet = "/home/jayson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
